language: ruby
cache: bundler

addons:
  postgresql: 9.3

rvm:
- 2.1.2

before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate


deploy:
  provider: cloud66
  redeployment_hook:
    production: "https://hooks.cloud66.com/stacks/redeploy/a10eaad53152560d60a989663c75cd6d/6fb2c8ed128c167d55205ec54cc9e884"